### DISCUSSION TITLE
How to add new api function app

### DISCUSSION THREAD

**Discussion by macik1423** [OfficeDev/microsoft-365-agents-toolkit#10744] [Q&A]
Hi, I am wondering what is the proper way to add new api function app, everywhere there is hardcoded `getUserProfile` example, what if I need `getUserProfile` and `getUsers`. How it should looks like in `teamsapp.local.yml`, `teamsapp.yml`? 
I mean that lines:
`teamsapp.yml:`
```
- uses: script
    with:
      run:
        echo "::set-teamsfx-env TAB_DOMAIN=localhost:53000";
        echo "::set-teamsfx-env TAB_ENDPOINT=https://localhost:53000";
this one -> echo "::set-teamsfx-env FUNC_NAME=getUserProfile";
        echo "::set-teamsfx-env FUNC_ENDPOINT=http://localhost:7071";
```

`teamsapp.local.yml:`
```
deploy:
  # Run npm command
  - uses: cli/runNpmCommand
    name: install dependencies
    with:
      args: install
  - uses: cli/runNpmCommand
    name: build app
    with:
      args: run build --if-present
    env:
      REACT_APP_CLIENT_ID: ${{AAD_APP_CLIENT_ID}}
      REACT_APP_START_LOGIN_PAGE_URL: ${{TAB_ENDPOINT}}/auth-start.html
this one  -> REACT_APP_FUNC_NAME: getUserProfile
      REACT_APP_FUNC_ENDPOINT: ${{API_FUNCTION_ENDPOINT}}
```
Should I change these variables to array of function app names?
If I add new folder with new api let say `getUsers`, provision for dev works fine, deploy as well. Function app in azure has `getUserProfile` and `getUsers` but how can I manage this in `config` file on local development?
Should it looks like this? :

`teamsapp.yml:`
```
- uses: script
    with:
      run:
        echo "::set-teamsfx-env TAB_DOMAIN=localhost:53000";
        echo "::set-teamsfx-env TAB_ENDPOINT=https://localhost:53000";
        echo "::set-teamsfx-env FUNC_NAME_1=getUserProfile";
        echo "::set-teamsfx-env FUNC_NAME_2=getUsers";
        echo "::set-teamsfx-env FUNC_ENDPOINT=http://localhost:7071";
```
`teamsapp.local.yml:`
```
deploy:
  # Run npm command
  - uses: cli/runNpmCommand
    name: install dependencies
    with:
      args: install
  - uses: cli/runNpmCommand
    name: build app
    with:
      args: run build --if-present
    env:
      REACT_APP_CLIENT_ID: ${{AAD_APP_CLIENT_ID}}
      REACT_APP_START_LOGIN_PAGE_URL: ${{TAB_ENDPOINT}}/auth-start.html
      REACT_APP_FUNC_NAME_1: getUserProfile
      REACT_APP_FUNC_NAME_2: getUsers
      REACT_APP_FUNC_ENDPOINT: ${{API_FUNCTION_ENDPOINT}}
```

`config.ts:`
```
const config = {
  initiateLoginEndpoint: process.env.REACT_APP_START_LOGIN_PAGE_URL,
  clientId: process.env.REACT_APP_CLIENT_ID,
  apiEndpoint: process.env.REACT_APP_FUNC_ENDPOINT,
  apiName_1: process.env.REACT_APP_FUNC_NAME_1,
  apiName_2: process.env.REACT_APP_FUNC_NAME_2,
};
```

`.env.local:`
```
...
FUNC_NAME_1=getUserProfile
FUNC_NAME_2=getUsers
...
```
