### DISCUSSION TITLE
Certificate trusted

### DISCUSSION THREAD

**Discussion by Valtikss** [OfficeDev/microsoft-365-agents-toolkit#11157] [Q&A]
In version 5.6.0, where can I disable this setting?  Thanks
![vsc-trust-dev-cert](https://github.com/OfficeDev/TeamsFx/assets/80110966/5d88369f-244d-45d1-a53a-0916e05ed07c)

**Comment by therealjohn** [comment]
@Valtikss In 5.x of Teams Toolkit, you can control this in the `teamsapp.local.yml` file. 

By default, for templates that have a Tab, there is a `devTool/install` action in the `deploy` lifecycle step which runs when you Start Debugging or F5. 

```yml
deploy:
  # Install development tool(s)
  - uses: devTool/install
    with:
      devCert:
        trust: true

...
```
You can change `trust:false` or comment/remove this action completely.
